%!PS-Adobe-3.0 EPSF-3.0
%%Creator: Adobe Photoshop Version 12.0x20100407 [20100407.r.1103 2010/04/07:14:00:00 cutoff; r branch]
%%Title: stretching-exercises.png
%%CreationDate: 2/17/2017 06:44 PM
%%BoundingBox: 0 0 49 49
%%HiResBoundingBox: 0 0 49.4865 49.4865
%%SuppressDotGainCompensation
%ADO_ContainsXMP: MainFirst
%%EndComments
%%BeginProlog
%%EndProlog
%%BeginSetup
%%EndSetup
%ImageData: 32 32 8 1 0 32 7 "beginimage"
gsave % EPS gsave
40 dict begin
/_image systemdict /image get def
/_setgray systemdict /setgray get def
/_currentgray systemdict /currentgray get def
/_settransfer systemdict /settransfer get def
/_currenttransfer systemdict /currenttransfer get def
/blank 0 _currenttransfer exec
1 _currenttransfer exec eq def
/negative blank
{0 _currenttransfer exec 0.5 lt}
{0 _currenttransfer exec 1 _currenttransfer exec gt}
ifelse def
/inverted? negative def
/level2 systemdict /languagelevel known
{languagelevel 2 ge} {false} ifelse def
/level3 systemdict /languagelevel known
{languagelevel 3 ge} {false} ifelse def
gsave % Image Header gsave
/rows 32 def
/cols 32 def
49.4865 49.4865 scale
level2 {
/DeviceGray
setcolorspace currentdict /PhotoshopDuotoneColorSpace undef currentdict /PhotoshopDuotoneAltColorSpace undef } if
/picstr1 32 string def
/_rowpadstr 32 string def
/rawreaddata {hasDecodeFile 0 eq {/decodeFile currentfile /ASCII85Decode filter def
                                  /hasDecodeFile 1 def} if
              decodeFile exch readstring pop} def
/padreaddata { _topPad 0 gt       { /_topPad _topPad 1 sub def pop _rowpadstr }
			 { _subImageRows 0 gt { /_subImageRows _subImageRows 1 sub def
									dup _leftPad _picsubstr rawreaddata putinterval }
								  { pop _rowpadstr } ifelse } ifelse } def
/image2 level2 {/image load def} {{begin
Width Height BitsPerComponent ImageMatrix
/DataSource load image end} def} ifelse
/beginimage level2 {{
image2
} def}
{{pop .9 setgray 0 0 moveto 0 1 lineto
1 1 lineto 1 0 lineto fill 0 setgray
0 1 translate 1 cols div 1 rows div scale
/ratio {cols 400 div mul} def
/Helvetica findfont 15 ratio scalefont setfont
5 ratio -20 ratio moveto
(ASCII85 encoded image needs PostScript Level 2) show
/x 128 string def
{currentfile x readline {} {pop exit} ifelse
(~>) search {pop pop pop exit} {pop} ifelse
} loop } def}
ifelse
/hasDecodeFile 0 def
/readdata /rawreaddata load bind def
12 dict begin
/ImageType 1 def
/Width cols def
/Height rows def
/ImageMatrix [cols 0 0 rows neg 0 rows] def
/BitsPerComponent 8 def
/Decode [0 1] def
/DataSource {picstr1 readdata} def
currentdict end
%%BeginBinary:       1314
beginimage
s8W-!s8W-!s8W-!s8W-!s8W-!s8VKAbI5=]s8W-!s8W-!s8W-!s8W-!s8W-!s8W,u
jLVLtYHG%Ps8W-!s8W-!s8W-!s8W-!s8W-!s8VZ"Y-+q1Y-,"es8W-!s8W-!s8W-!
s8W-!s8W-!s5^DfY-+qKhX(+=s8W-!s8W-!s8W-!s8W-!s8W-!hla,bYLr[Ns8W-!
s8W-!s8W-!s8W-!s8W-!s8W,fYck4?oCgl+s8W-!s8W-!s8W-!s8W-!s8W-!s8Vu'
Y-,>4i30;deGoRKs8W-!s8W-!s8W-!s8W-!s8UBIY-Rd$\ZW*<Z2FY%s8W-!s8W-!
s8W-!s8W-!s6d%nY.=B,['$R7YPJ4us8W-!s8W-!s8W-!s8W-!s1GM;Y-,51f<29Z
b5_MAs8W-!s8W-!s8W-!s8W-!godf_Y-+tRrohPcr;Zfss8W-!s8W-!s8W-!s8W,p
Z*(:5Y-+t3gAh3Qs8W-!s8W-!s8W-!s8W-!s8W,NY-5%3YHP.5Y2oW_s8W-!s8W-!
s8W-!s8W-!s8W#&Y-+t2Y-5RBYH[s)s8W-!s8W-!s8W-!s8W-!s8V#[Y-+q2YMf2]
YHHg`s8W-!s8W-!s8W-!s8W-!s8TO1YHP+4_<]piY-5J;s8W-!s8W-!s8W-!s8W-!
s5pJeY-5"2Y-+q1Y-5#+s8W-!s8W-!s8W-!s8W-!s1YY=Y-+q2Y-5"2Y--+Ns8W-!
s8W-!s8W-!s8W-!m&mOpY-+t2Y.)U/lM:J[s8W-!s8W-!s8W-!s8W-!`NHAHY-,,$
qu?]rs8W-!s8W-!s8W-!s8W-!s8W,iY-+t2Y-5"ls8W-!s8W-!s8W-!s8W-!s8W-!
s8W,CYHG%6Y-5"Es8W-!s8W-!s8W-!s8W-!s8W-!s8VnuYHP+qYHG%2n,NFfs8W-!
s8W-!s8W-!s8W-!s8U]RY-,\BdB9XUaT);?s8W-!s8W-!s8W-!s8W-!s8TL1YHI$f
p9(U&Y4Vbos8W-!s8W-!s8W-!s8W-!s6QnkYHn-,s3%RJY0R(Is8W-!s8W-!s8W-!
s8W-!s3@gNY1!@Ms73=rYH[g%s8W-!s8W-!s8W-!s8W-!r33?,Y4DVms8U'@Y--=T
s8W-!s8W-!s8W-!s8W-!jK>Yg^An65s8VGgY-,#,s8W-!s8W-!s8W-!s8W-!d''UT
i;`iWs8W,5YHG&%s8W-!s8W-!s8W-!s8W-!eZQ'[qu?]rs8W,aY-,;3s8W-!s8W-!
s8W-!s8W-!r6)\<s8W-!s8W-!m+h@8s8W-!s8W-!s8W-!~>
%%EndBinary
grestore end % Image Trailer grestore
grestore % EPS grestore
